// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated for the UrlShortener project.
//     File: AdminController.cs
//     Description: Controller for admin operations on shortened URLs.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace UrlShortener.API.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using UrlShortener.Core.Repositories;
    using UrlShortener.Core.Entities;
    using Microsoft.AspNetCore.Http;

    [ApiController]
    [Route("api/admin")]
    public class AdminController : ControllerBase
    {
        private readonly IShortenedUrlRepository _urlRepository;
        private readonly IUserRepository _userRepository;
        private const string AdminApiKey = "admin-secret-key"; // TODO: move to config

        public AdminController(IShortenedUrlRepository urlRepository, IUserRepository userRepository)
        {
            _urlRepository = urlRepository;
            _userRepository = userRepository;
        }

        private bool IsAdmin(HttpRequest request)
        {
            if (request.Headers.TryGetValue("X-Api-Key", out var apiKey))
            {
                return apiKey == AdminApiKey;
            }
            return false;
        }

        [HttpGet("links")]
        public async Task<IActionResult> GetAllLinks()
        {
            if (!IsAdmin(Request))
                return Unauthorized("Admin API key required");
            var links = await _urlRepository.GetAllAsync();
            return Ok(links);
        }

        [HttpDelete("links/{shortCode}")]
        public async Task<IActionResult> DeleteLink(string shortCode)
        {
            if (!IsAdmin(Request))
                return Unauthorized("Admin API key required");
            await _urlRepository.DeleteByShortCodeAsync(shortCode);
            return NoContent();
        }
    }
}
