// ------------------------------------------------------------------------------
//  <auto-generated>
//      This file is part of the UrlShortener project.
//      (c) 2024 Semen Arshyn. All rights reserved.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace UrlShortener.API.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using System.Threading.Tasks;
    using UrlShortener.Core.Repositories;

    [ApiController]
    public class RedirectController : ControllerBase
    {
        private readonly IShortenedUrlRepository _repository;

        public RedirectController(IShortenedUrlRepository repository)
        {
            _repository = repository;
        }

        /// <summary>
        /// Redirects to the original URL by short code.
        /// </summary>
        [HttpGet("/{shortCode}")]
        public async Task<IActionResult> RedirectToOriginal(string shortCode)
        {
            var entity = await _repository.GetByShortCodeAsync(shortCode);
            if (entity == null)
                return NotFound();

            if (entity.IsBlocked)
                return StatusCode(403, "This link is blocked by admin.");

            entity.ClicksCount++;
            await _repository.UpdateAsync(entity);

            return Redirect(entity.OriginalUrl);
        }
    }
}
